### PR TITLE
Fix Empty OP_RETURN Errors

### PR DESCRIPTION
**Pull request by jwicks31**
[PR Process](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-process) - [PR Review Checklist](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-review-checklist)

### Release
 Semantic release is enabled for this repository. Make sure you follow the right commit message convention. 
 We're using semantic-release's default — [Angular Commit Message Conventions](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines).

## Description of Changes

Modified dataOutputToData to fix error

### CODE REVIEW

**Comment by kennylavender** [comment]
@jwicks31 can you add a quick comment explaining the difference we found between the insight-api and the bitcore-api as just an FYI

**Comment by jwicks31** [comment]
@kennylavender Yep. Do you have a preference on where that is added? Just above the block in the blocks file?

**Comment by kennylavender** [comment]
Sorry I meant in this PR as a comment, not in the code :)

**Comment by jwicks31** [comment]
Oops ok. 

Pulling this block information from Insight-API offered different results than with using the Bitcoin-Core-API. The transactions scriptPubKey property did not include a type for several transactions when using Insight-API, but it was included with the Bitcoin-Core-API.

**Pull request merged**
