### PR TITLE
chore: update docker-compose env vars

### LINKED ISSUE #436: Update docker-compose env vars
Update docker-compose with env vars to stop errors from blockcainReader/Writer and allow integration tests to run inside the container.

### PR DESCRIPTION
**Pull request by warrenv**
### Release
 Semantic release is enabled for this repository. Make sure you follow the right commit message convention. 
 We're using semantic-release's default — [Angular Commit Message Conventions](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines).

## Description of Changes

Fixes #436

This commit sets environment variables on the poet-node service
to allow integration tests to run inside the poet-node container.
It also sets BITCOIN_URL to fix several erros similar to this on
`npm start`:

[2018-09-13T16:06:40.469Z] ERROR (143 on poet-node): Uncaught Error
   module: "BlockchainReader"
   file: "BlockchainReaderService"
   method: "scanNewBlock"
   error: {
     "stack": [
       "TypeError: undefined is not a function",
       "    at Array.map (<anonymous>)",
       "    at ClaimController.scanBlock
(/usr/src/app/dist/babel/src/BlockchainReader/ClaimController.js:51:51)",
       "    at process._tickCallback
(internal/process/next_tick.js:68:7)"
     ],
     "message": "undefined is not a function",
     "type": "TypeError"
   }
   blockHeight: 1279551
   lastBlockHeight: 1279550

[PR Process](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-process) - [PR Review Checklist](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-review-checklist)

### CODE REVIEW

**Comment by geoffturk** [comment]
Can we also setup bitcoin-regtest so it already has 101 blocks mined, and therefore some spending funds in it?

**Comment by geoffturk** [comment]
FYI, I tried changing these values by passing them in as env vars in docker-compose.yml but they are being interpreted as strings rather than integers. :-/

**Comment by warrenv** [comment]
I'm working on changing the other variables as part of the functional testing PR.
The purpose of this Pr is just to get the integration tests running in the container.

**Comment by geoffturk** [comment]
OK.

**Pull request merged**
