### PR TITLE
npm run create-claim

### PR DESCRIPTION
**Pull request by lautarodragan**
[PR Process](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-process) - [PR Review Checklist](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-review-checklist)

### Release
 Semantic release is enabled for this repository. Make sure you follow the right commit message convention. 
 We're using semantic-release's default — [Angular Commit Message Conventions](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines).

## Description of Changes

Fixes https://github.com/poetapp/node/issues/426

Usage: `npm run create-claim <title> <author>`.

Both arguments are optional.

To be used manually, for testing purposes only.

### CODE REVIEW

**Comment by kennylavender** [comment]
looks fine to me, maybe a different folder or sub folder because it's not a test?

**Comment by lautarodragan** [comment]
maybe `scripts`?

**Comment by kennylavender** [comment]
scripts works for me

**Comment by lautarodragan** [comment]
fixed!

**Pull request merged**
